apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "todo-app.fullname" . }}-app-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "todo-app.labels" . | nindent 4 }}
data:
  BACKEND_API_URL: "http://{{ include "todo-app.fullname" . }}-backend-service:8000"
  CHATBOT_API_URL: "http://{{ include "todo-app.fullname" . }}-chatbot-service:8001"
  DATABASE_URL: "postgresql://{{ include "todo-app.fullname" . }}-db-service:5432/todoapp"